server:
  port: 8081

user-service:
  url: http://USER-SERVICE/user

spring:
  application:
    name: BOOKING-SERVICE

eureka:
  client:
    service-url:
      defaultUrl: ${EUREKA_URI:http://localhost:8761/eureka/}
    instance:
      preferIpAddress: true
