server:
  port: 8081

user-service:
  url: http://USER-SERVICE/api/v1/user

spring:
  application:
    name: BOOKING-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_service_db
    username: postgres
    password: 4999
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10KB
      max-file-size: 300MB
      max-request-size: 450MB

eureka:
  client:
    service-url:
      defaultUrl: ${EUREKA_URI:http://localhost:8761/eureka/}
    instance:
      preferIpAddress: true
